apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    version: 1

  - name: PostgreSQL
    type: prometheus
    access: proxy
    url: http://postgres-exporter:9187
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
    version: 1
    hidden: false

  - name: Redis
    type: prometheus
    access: proxy
    url: http://redis-exporter:9121
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
    version: 1
    hidden: false

  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
    version: 1
    hidden: false

  - name: cAdvisor
    type: prometheus
    access: proxy
    url: http://cadvisor:8080
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
    version: 1
    hidden: false
